### PR TITLE
Make test env fully configurable (logging, etc.)

### PR DESCRIPTION
**Pull request by e2**
- sane defaults regarding logging/output (Travis, dev)
- different logging stragies (split, single, stderr)
- use Nenv and Dotenv gems for handling ENV config
- fix spec which didn't shutdown actor system
- mark regularly failing Probe spec as flaky

### CODE REVIEW

**Comment by e2** [comment]
Crashes are now on STDERR in Travis - generally, the logger should be stubbed in tests that purposely crash, so they'll need to be fixed.

Once those specs are fixed, the next step would be to fail if *any* unhandled crashes occur during dev.

**Comment by e2** [comment]
Feel free to add config files with any "profile" you think is useful. 

E.g I don't like split files based on timestamps - and you can't do `tail -f log/test.log`, and finding the right log just to see a "NoMethodError" introduced during refactoring ... is just a PITA.

Split logs feels like a good idea, but it isn't practical - no matter how I approach it.

It depends on your workflow really - I've prepared '.env-ci' (for Travis) and '.env-dev' (for contributors) mostly as examples. You can override values at the commandline, anyway.

**Comment by digitalextremist** [comment]
@e2 I've been having the same problem with `rspec-split_log` too, in practice. I think it might be good to pass an `ENV` flag to select between a single file and the various split files.

**Comment by e2** [comment]
@digitalextremist - that's how it works now. Checkout out the `.env-dev` and `.env-ci` files (CELLULOID_SPECS_LOG_STRATEGY=split or single or stderr)

**Comment by e2** [comment]
There should be a wiki entry for this stuff (debugging and development) - though I believe in good defaults for conventions people expect.

E.g. variables such as `CELLULOID_TASK_CLASS` should be in an `.env` file - this is already possible, just that only tests load the `.env-*` files right now.

**Comment by e2** [comment]
I'll maybe move the env vars from travis.yml into separate config files.

**Pull request merged**
