### PR TITLE
spec config (retries, thread leaks) + fix leaks

### PR DESCRIPTION
**Pull request by e2**
- misc thread leak fixes
- fail on thread leaks in specs
- refactor RSpec config

### CODE REVIEW

**Comment by digitalextremist** [comment]
@e2 this is failing primarily on "no `terminate!` on `nil`"

**Comment by e2** [comment]
@digitalextremist - yeah, I was slamming the probe specs so much, that I forgot to test everything else. (Here, the actor_system tests need a "special" setup to play nicely).

**Comment by e2** [comment]
@digitalextremist - anything you can do about this?

https://travis-ci.org/abstractive/celluloid/jobs/58031672

I think the gem cache on Travis is borked for rspec-log_split.

(Maybe just a single no-op commit to master would get it restarted?)

**Comment by digitalextremist** [comment]
@e2 I'll unbork that. Finally in the office for a serious period of time.

**Comment by e2** [comment]
@digitalextremist - if you untagle ruby-head on Travis (bundler issue), and I finish merging the improved Pool (and adaptations) ... we might be seeing green from top to bottom for the first time.

**Comment by digitalextremist** [comment]
I'm excited @e2, finishing an email then I'm all over it.

**Comment by digitalextremist** [comment]
Ok I'm actively involved with this.

**Comment by digitalextremist** [comment]
Merging this in to patch onto for unborking.

**Comment by digitalextremist** [comment]
Tracking bundler issue at bundler/bundler#3558 also.

**Comment by digitalextremist** [comment]
Resolved this, but bundler is going to be broken until it gets re-cut: bundler/bundler#3559

**Comment by digitalextremist** [comment]
@e2 for now, consider `ruby-head` broken, because either bundler or rubygems ( or both ) are borked. I tried a patch, and at first it worked, but then it broke their whole test suite. So I'll let that resolve itself.

**Comment by digitalextremist** [comment]
I overrode `rspec-log_split` and as expected, the same problem under `ruby-head` moved to `timers` instead. It's a core issue with `rubygems` and/or `bundler` like I said. I put together a bone-head first-pass patch and at first it fixed it, but then either something changed again to dislodge my fix, or my fix didn't fix it. Either will pass this or try to fix it. Since I seem to be a glutton for punishment today I'll probably try again to fix it.

**Comment by digitalextremist** [comment]
rubygems/rubygems#1220

**Comment by e2** [comment]
@digitalextremist - could be just borked gem cache on the Travis aufs snapshot for ruby-head. Maybe switching away from aufs containers and back would help (`sudo: false` option in `.travis.yml`). Probably best to report to Travis, though :+1: for fixing this in RubyGems (it should fix it's cache if necessary).

**Comment by digitalextremist** [comment]
@e2 it was borked locally as well as in CI... so doesn't seem like Travis is the bork point. Waiting for feedback from `bundler` and/or `rubygems` to see `ruby-head` light up green.

**Comment by e2** [comment]
> it was borked locally as well as in CI
great to hear that - thanks!

**Pull request merged**
