### PR TITLE
add missing block param in SyncCall (#554)

### PR DESCRIPTION
**Pull request by e2**
- add test + fix smokers example (localjump error)

### CODE REVIEW

**Comment by e2** [comment]
@digitalextremist - what happened to Travis?

**Comment by e2** [comment]
@digitalextremist - this is rebased against celluloid/0.17.0-prerelease. I'll continue with other changes onto an "experimental" branch here: https://github.com/abstractive/celluloid/tree/e2-experimental

You have a lot to deal with regarding the release - so let me know how to proceed so I don't get in your way.

**Comment by digitalextremist** [comment]
@e2 thanks, yeah; ok. I'm back at the lab now, so I'm merging the fix and working further.

**Comment by digitalextremist** [comment]
This was done separately, so this should be behind ( with all changes made here, moved to 0.17.0-prerelease )

**Pull request closed without merging**
